set config(daemon)      1
set config(auto)        1
set config(system_status)   1
set config(nouserconfig)    1

# Penjelasan Level Kipas Dell: 0 (Mati), 1 (Sedang), 2 (Kencang Maksimal)
# Format: {{kipas_kiri kipas_kanan} suhu_bawah suhu_atas suhu_bawah_AC suhu_atas_AC}

# Level 0: Kipas Mati (Saat suhu di bawah 39°C)
set config(0)   {{0 0}  -1  39  -1  39}

# Level 1: Kipas Sedang (Aktif saat suhu 45°C - 65°C)
set config(1)   {{1 1}  45  65  45  65}

# Level 2: Kipas Ngebut (Aktif saat suhu menyentuh 75°C ke atas)
set config(2)   {{2 2}  65  128  65  128}
